- .travis.yml
> add manylinux2010 distribution for faiss-cpu

- .github/workflows/build.yml
- README.md
- setup.py
- Environment variable to control avx2 compile flags
- Rename `BUILD_CUDA` to `ENABLE_CUDA`
- Update README
> Add build option for avx2

- setup.py
> Delay numpy import in setup.py

- .github/workflows/build.yml
- setup.py
Fix broken sdist package (Fix #25 )
> Fix source package install

- .github/workflows/build.yml
- README.md
- setup.py
Fix minor wheel issues #28 #27
> v1.6.4 post release 2

- .github/workflows/build.yml
- setup.py
- Update faiss to v1.6.5
- Minor `setup.py` fix
> Update faiss to v1.6.5

- .github/workflows/build.yml
- Reduce GPU package size (Fix #34)
> Reduce GPU package size

- .github/workflows/build.yml
- setup.cfg
- setup.py
- Upgrade faiss to v1.7.1
- Use conda openblas instead of manual build
- Fix windows DLL dependency by `delvewheel` (Fix #38)
- Use `delocate` in mac
> faiss v1.7.1

- .github/workflows/build.yml
- setup.py
Attempt to fix #42 
- add conda path to delvewheel
> Fix missing DLLs in windows

- .github/workflows/build.yml
- scripts/build_macOS.sh
- setup.py
- Fix `CMAKE_OSX_ARCHITECTURES` flag for cross compilation
- Add libomp build step
> Fix macOS arm64 build

- .github/workflows/build.yml
- scripts/build_Linux.sh
- setup.py
Changes
- [Update faiss version to v1.7.2](https://github.com/facebookresearch/faiss/releases/tag/v1.7.2)
Details
- add doxygen flag in swig option (facebookresearch/faiss#1969)
- add curand dependency (facebookresearch/faiss#1978)
> Update faiss to v1.7.2 release

- README.md
- pyproject.toml
- scripts/build_macOS.sh
- setup.py
Changes:
- Upgrade faiss to v1.7.4
> Version v1.7.4

- .github/workflows/build.yml
- .gitignore
- README.md
- patch/faiss-remove-lapack.patch
- pyproject.toml
- setup.py
Changes:
- Update `actions/checkout` to `v4`
- Update `actions/setup-python` to `v5`
- Use `cibuildwheel=2.16.2`
- Migrate metadata to `pyproject.toml`
- Fix build configuration for the latest faiss
- Disable unstable windows tests
> Update CI dependencies

- .github/workflows/build.yml
- README.md
- pyproject.toml
- setup.py
Changes:
- Update upstream to the latest
- Refactor `setup.py` to support avx512 extension
> Support AVX512

- .github/workflows/build.yml
- pyproject.toml
- scripts/build_Windows.sh
- setup.py
Changes:
- Sync upstream to v1.8.0
- Enable Windows avx2 build
> Sync upstream to v1.8.0

- .github/workflows/build.yml
Changes:
- Add missing environment key
> Fix missing environment in PyPI upload

- pyproject.toml
Refs:
- https://github.com/kyamagu/faiss-wheels/issues/104
> Pin to NumPy <2.0

- pyproject.toml
Changes:
- Add missing `packaging` dependency` in the package
- Explicitly specify numpy version requirement
- Fix CI errors
This release does not change the functionality and only resolves the dependency issues
> v1.8.0 post release 1

- .github/workflows/build.yml
- pyproject.toml
Changes:
- Support CPython 3.13 wheels
> Support CPython 3.13

- .github/workflows/build.yml
- patch/faiss-remove-lapack.patch
- pyproject.toml
- scripts/build_Linux.sh
- setup.py
Changes:
- Update the bundled [faiss](https://github.com/facebookresearch/faiss) to v1.10.0
- Enable aarch64 tests
> Update faiss to v1.10.0

- .github/workflows/build.yml
- pyproject.toml
- scripts/build_Windows.sh
- scripts/build_macOS.sh
- setup.py
Changes:
- Upgrade faiss to v1.11.0
- Remove unused macOS cross-compiling setup
- Update CI dependencies
> v1.11.0 release

- setup.py
During the build, use the `FAISS_BLAS` environment variable to select between FlexiBLAS or OpenBLAS.
> support FlexiBLAS as an alternative to OpenBLAS
